"""``events emit`` — validate an envelope through the core, then publish it QoS 1.

Translation layer over three domain seams: :mod:`events_cli.core.envelope` (the
trust boundary that decides whether the envelope is even well formed),
:mod:`events_cli.core.topics` (the one place a ``type`` becomes a topic), and
:class:`events_cli.client.EventClient` (the transport). Nothing here invents a
topic string or a validation rule; it only assembles the payload, validates it,
and reports what the publish did.

The ``--data`` shape decision
------------------------------
``--data`` is **only the event's ``data`` payload**, not a whole envelope.
``events emit task.requested --data task.json`` reads as "emit a
``task.requested`` event whose data is the contents of ``task.json``" — issue
#1's own example, and the natural reading of a positional ``type`` next to a
``--data`` flag. The alternative (``--data`` holding a *complete* envelope,
``id``/``time`` and all) would make the positional ``type`` redundant with
whatever the file already says, and would force a choice about which one wins.
It would also conflict with generating ``id``/``time`` here: this command
mints both itself, the same way :meth:`~events_cli.core.envelope.Envelope.new`
would, and a file that already carried them would have to be silently
overridden or silently deferred to — neither is a clean contract. Absent
``--data``, the payload defaults to ``{}``, a valid empty object.

Every problem ``--data``'s *content* can have (not an object, unsupported JSON
value, too deep, ...) is left to :meth:`Envelope.from_dict` to report as a
field-level error under the ``data`` field — one validator, not two that could
disagree. Only "the file could not be read" and "the bytes are not JSON at
all" are caught here, because :meth:`Envelope.from_dict` has no way to see
either: it only ever receives an already-parsed Python value.

Building the payload through ``Envelope.from_dict``, not ``Envelope.new``
---------------------------------------------------------------------------
The generated ``id``/``time`` plus the positional ``type``, the resolved
``source`` and any tracing flags are assembled into the exact wire-shaped dict
first, and *that* dict is handed to :meth:`Envelope.from_dict` — the same trust
boundary anything arriving over the wire goes through — rather than calling
:meth:`Envelope.new` (which validates internally but does not go through
``from_dict``). The point is symmetry: an envelope this command builds is
validated by precisely the same code path as an envelope read back from a
transport, a file, or a stored record, so there is exactly one place "is this
envelope valid" is decided.

Tracing flags
-------------
``--correlation-id``/``--causation-id``/``--run-id`` are exposed now, not
deferred. Issue #1's motivating flow
(``task.requested -> scope.completed -> ... -> validation.completed``) is
useless without them — an emitted event that cannot be correlated to what
caused it is half the contract. ``--producer``/``--traceparent``/
``--schema-version`` are not exposed: they are either rarely hand-typed
(``traceparent`` is generated by a tracing library, not a human) or have a
sensible fixed default (``schemaVersion``), and the flag surface stays small
until a real caller asks for more.

Publishing is always QoS 1, never a flag
------------------------------------------
This is the whole point of the q3 decision :mod:`events_cli.client` documents:
an envelope published at QoS 0 is never queued for an offline persistent
session, so it silently bypasses durable capture. Making QoS a flag here would
let a caller quietly opt back into that trap; ``emit`` always passes ``qos=1``
to :meth:`~events_cli.client.EventClient.publish_event`, unconditionally.

A failed publish is an environment fault, not a user error
-------------------------------------------------------------
Once the envelope validates, nothing about a broker-down publish is the
caller's mistake — the invocation was fine, the host is not in a state where it
can succeed, exactly the exit-2 category :mod:`events_cli.cli._errors`
documents. Following ``cmd_up``/``cmd_status``'s precedent
(``events_cli/cli/_commands/stack.py``), the result is still emitted to stdout
either way — the envelope was validated and an attempt was made, and the
caller (especially an agent) needs the ``id``, the topic and the failure reason
to decide what to do next — and only the *exit code* carries the failure,
via a plain ``return``, never a :class:`~events_cli.cli._errors.CliError`
(which would route the payload to stderr instead and mix the two streams).
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

from events_cli.cli._errors import EXIT_ENV_ERROR, EXIT_USER_ERROR, CliError
from events_cli.cli._output import emit_result
from events_cli.cli._prog import prog_name
from events_cli.client import EventClient, PublishResult
from events_cli.core import (
    SCHEMA_VERSION,
    Envelope,
    EnvelopeValidationError,
    new_event_id,
    now_rfc3339,
    read_agent_fields,
    type_to_topic,
)

__all__ = ["cmd_emit", "register"]

#: publishing at anything less than QoS 1 is exactly the capture trap this
#: verb exists to close (see the module docstring) — never a flag.
_EMIT_QOS = 1

_STDIN_MARKER = "-"

#: How long ``emit`` waits for the asynchronous connection to come up, and then
#: for the broker to acknowledge the publish. Two separate budgets because they
#: fail differently and an operator should be able to tell them apart: no
#: connection at all is "the broker is not there" (``connected=false``), an
#: unconfirmed publish is "it is there and did not answer" (``unconfirmed``).
#: Finite by policy — an unbounded wait is what hangs an agent turn.
_CONNECT_WAIT = 10.0
_DELIVERY_WAIT = 10.0

#: How often to re-check the connection while waiting. Small enough that a local
#: broker costs a millisecond or two, large enough not to spin a core.
_POLL_INTERVAL = 0.02


def _read_data(source: str | None) -> object:
    """Parse ``--data`` into the value that becomes the envelope's ``data`` field.

    Absent ``--data``, the payload is ``{}``. ``'-'`` reads stdin; anything
    else is a file path. Only "unreadable" and "not JSON at all" are handled
    here — everything about the parsed value's *shape* (not an object, a value
    JSON cannot represent, ...) is left for :meth:`Envelope.from_dict` to
    report as a field-level error, so there is one validator, not two.
    """
    if source is None:
        return {}

    if source == _STDIN_MARKER:
        text = sys.stdin.read()
    else:
        path = Path(source)
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as exc:
            raise CliError(
                code=EXIT_USER_ERROR,
                message=f"--data {source!r} could not be read: {exc}",
                remediation="pass a path to a readable JSON file, or '-' to read JSON from stdin",
            ) from exc

    try:
        return json.loads(text)
    except json.JSONDecodeError as exc:
        raise CliError(
            code=EXIT_USER_ERROR,
            message=f"--data is not valid JSON: {exc}",
            remediation="--data must be a JSON document (an object, by convention)",
        ) from exc


def _default_source() -> str:
    """``agent://<this agent's culture.yaml nick>`` — the same nick ``events whoami`` reports.

    Falls back to ``agent://events-cli`` (the literal
    :data:`~events_cli.core.identity.FALLBACK_NICK`) when no ``culture.yaml``
    ships alongside the package, e.g. a wheel install — :func:`read_agent_fields`
    already encodes that fallback, so it is reused rather than re-derived.
    """
    return f"agent://{read_agent_fields()['nick']}"


def _await_connection(client: EventClient, timeout: float) -> None:
    """Block until the client is connected, or the bound expires. Never raises.

    Deliberately here and not in :class:`~events_cli.client.EventClient`: that
    class must never block, because its defining consumer publishes from inside
    a 50 Hz robot control loop. A one-shot CLI invocation is the opposite case
    and owns its own waiting.
    """
    deadline = time.monotonic() + timeout
    while not client.is_connected and time.monotonic() < deadline:
        time.sleep(_POLL_INTERVAL)


def _publish(envelope: Envelope, topic: str) -> PublishResult:
    """The only place ``emit`` touches the network. Tests monkeypatch this.

    A short-lived client: ``emit`` is a one-shot CLI invocation, not a
    long-running producer, so there is no standing connection to reuse between
    calls and every reason to close it before the process exits.

    That one-shot shape is why this blocks twice, where the importable client
    never does — and both waits are load-bearing, not defensive:

    1. **Wait for the connection.** :class:`~events_cli.client.EventClient`
       connects *asynchronously* (``connect_async`` plus a background loop), so
       a publish issued in the same breath as the constructor is always issued
       while still disconnected. Without this wait ``emit`` reported
       ``connected=false``/``no_conn`` and exited 2 against a perfectly healthy
       broker, every single time — and the message, queued inside paho, was then
       discarded by the ``close()`` below. Every existing unit test replaces
       ``EventClient`` with a fake, so only the docker-backed round-trip in
       ``tests/test_subs_integration.py`` could see it.
    2. **Wait for the broker to take the message.** paho's own ``loop_stop``
       docstring: "This don't guarantee that publish packet are sent, use
       ``wait_for_publish`` or ``on_publish`` to ensure publish are sent." A
       process that publishes and exits therefore has to wait, or it can report
       success for bytes that never left.

    Both bounds are finite, like every other bound in this repo: a broker that
    is down costs ``_CONNECT_WAIT`` seconds and then reports a clean exit-2
    failure rather than hanging the caller.
    """
    client = EventClient()
    try:
        _await_connection(client, _CONNECT_WAIT)
        return client.publish_event(envelope, topic, qos=_EMIT_QOS, wait=_DELIVERY_WAIT)
    finally:
        client.close()


def _emit(payload: dict[str, object], lines: list[str], *, json_mode: bool) -> None:
    if json_mode:
        emit_result(payload, json_mode=True)
    else:
        emit_result("\n".join(lines), json_mode=False)


def cmd_emit(args: argparse.Namespace) -> int:
    json_mode = bool(args.json)
    data = _read_data(args.data)

    wire: dict[str, object] = {
        "id": new_event_id(),
        "type": args.type,
        "source": args.source if args.source is not None else _default_source(),
        "time": now_rfc3339(),
        "schemaVersion": SCHEMA_VERSION,
        "data": data,
    }
    if args.correlation_id is not None:
        wire["correlationId"] = args.correlation_id
    if args.causation_id is not None:
        wire["causationId"] = args.causation_id
    if args.run_id is not None:
        wire["runId"] = args.run_id

    try:
        envelope = Envelope.from_dict(wire)
    except EnvelopeValidationError as exc:
        # str(exc) already lists every field-level reason (see
        # EnvelopeValidationError.__str__), so nothing is lost by folding it
        # into one CliError message; no publish has been attempted.
        raise CliError(
            code=EXIT_USER_ERROR,
            message=str(exc),
            remediation="fix the listed field(s) and retry; nothing was published",
        ) from exc

    # type_to_topic reuses the identical grammar Envelope.from_dict just
    # validated `type` with (see events_cli/core/topics.py's module docstring),
    # so a type good enough to pass validation above is always good enough to
    # route here — this cannot raise.
    topic = type_to_topic(envelope.type)
    result = _publish(envelope, topic)

    payload: dict[str, object] = {
        "event": envelope.to_dict(),
        "topic": topic,
        "qos": _EMIT_QOS,
        "publish": {
            "ok": result.ok,
            "connected": result.connected,
            "reason": result.reason,
            "mid": result.mid,
        },
    }
    lines = [
        f"emit {envelope.type}  id={envelope.id}",
        f"  topic:      {topic}",
        f"  qos:        {_EMIT_QOS}",
        f"  ok:         {result.ok}",
        f"  reason:     {result.reason}",
    ]
    if not result.ok:
        lines.append(f"  connected:  {result.connected}")
    lines.append("")
    lines.append(f"next: {prog_name()} get {envelope.id}")
    _emit(payload, lines, json_mode=json_mode)

    # A failed publish is an environment fault (the broker is not there to
    # accept it), not a user error — the envelope was valid. See the module
    # docstring for why this is a plain return, not a CliError.
    return 0 if result.ok else EXIT_ENV_ERROR


def register(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser(
        "emit",
        help="Validate an envelope through the core, then publish it QoS 1 to its topic.",
    )
    p.add_argument("type", help="Dotted event type, e.g. 'task.requested'.")
    p.add_argument(
        "--data",
        metavar="FILE",
        default=None,
        help="Path to a JSON file for the event's 'data' payload, or '-' to read JSON from "
        "stdin. Defaults to an empty object.",
    )
    p.add_argument(
        "--source",
        metavar="URI",
        default=None,
        help="Absolute URI identifying the producer, e.g. 'agent://builder'. Defaults to "
        "this agent's own 'agent://<culture.yaml nick>'.",
    )
    p.add_argument(
        "--correlation-id",
        metavar="ID",
        default=None,
        help="Ties this event to the request/flow it belongs to.",
    )
    p.add_argument(
        "--causation-id",
        metavar="ID",
        default=None,
        help="The id of the event that directly caused this one.",
    )
    p.add_argument(
        "--run-id",
        metavar="ID",
        default=None,
        help="Groups every event of one pipeline run together.",
    )
    p.add_argument("--json", action="store_true", help="Emit structured JSON.")
    p.set_defaults(func=cmd_emit)
